# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustDraw' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  # ignore all warnings from all pods
  inhibit_all_warnings!

  # Pods for JustDraw
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxDataSources'
  pod 'Moya'
  pod 'IQKeyboardManagerSwift'
  pod 'Kingfisher'
  pod 'ReachabilitySwift'
  pod 'PKHUD'
  pod 'Firebase/Core'
  pod 'Fabric'
  pod 'Firebase/Crash'
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'Crashlytics'
  pod 'CarbonKit'
  pod 'SnapKit'
  pod 'RealmSwift'
  pod 'DropDown'
  pod 'youtube-ios-player-helper'
  pod 'Device'
  pod 'FBSDKCoreKit'

  target 'JustDrawTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustDrawUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
